### ISSUE TITLE
The nessie ui is not working with authentication

### ISSUE THREAD

**Issue by HiIamBao** [projectnessie/nessie-ui#162]
Can i access the nessie UI when enabling authentication ?

**Comment by daha** [comment]
It works for me when I have configured it like described here: 
https://projectnessie.org/nessie-latest/authentication/?h=#openid-bearer-tokens

**Comment by adutra** [comment]
@HiIamBao after reading through the link above, are things working for you now? Can we close this one?

**Comment by HiIamBao** [comment]
@adutra @daha Oh it just working great, thank you so much for this update, i will close it now
